version: '3'
services:
  client:
    build:
      context: .
    container_name: rememberme-client-dev
    environment:
      NODE_ENV: 'development'
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - 8100:8100
      - 35729:35729
      - 53703:53703
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "1"
    command: npm run ionic:serve
