version: '3'
volumes:
  client:
services:
  client:
    build:
      context: .
    container_name: rememberme-client
    environment:
      NODE_ENV: 'development'
    volumes:
      - client:/app
      - /app/node_modules
    ports:
      - 8100:8100
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "1"
    command: npm run serve -r 8100
